# In this config, we don't have seperate samples for r2 or r3, we just combine them
variables: !include variables.yaml
#transform: !include transform.yaml

ttbar: &ttbar
    name: ttbar
    pattern:
        - "*.h5"


global_cuts:
  train:
    - [eventNumber, "%10<=", 7]
  val:
    - [eventNumber, "%10==", 8]
  test:
    - [eventNumber, "%10==", 9]

lowpt: &lowpt
  name: lowpt
  cuts:
    - [pt_btagJes, ">", 20_000]
    - [pt_btagJes, "<", 250_000]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [strangejets, downjets]
    num_jets: 10_000_000

resampling:
  target: strangejets
  method: pdf
  sampling_fraction: auto
  variables:
    pt_btagJes:
      bins: [[20_000, 250_000, 50]]
    absEta_btagJes:
      bins: [[0, 2.5, 20]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: jets
  batch_size: 1_000_000
  num_jets_estimate: 5_000_000
  base_dir: /home/db466094/Documnets/UPP/results
  ntuple_dir: /home/db466094/s-tagging/user.nekumari.601229.e8514_s4162_r14622_p5770.tdd.EMPFlow.24_2_14.23-08-14_PFlow_Aug_23_output.h5
